# Generated by Django 4.0.1 on 2022-05-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('category', models.IntegerField(choices=[(0, 'ERC721'), (1, 'ERC1155')])),
                ('decimals', models.IntegerField(default=0)),
                ('abi', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('animation_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=None, null=True)),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='metadata.smartcontract')),
            ],
            options={
                'unique_together': {('token_id', 'smart_contract')},
                'index_together': {('token_id', 'smart_contract')},
            },
        ),
    ]
